# Generated by Django 4.2.3 on 2023-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
