# Generated by Django 4.2.3 on 2023-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_alter_blog_created_at_alter_blog_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
